### ISSUE TITLE
API fails when IP is malformed

### ISSUE THREAD

**Issue by meyerzinn** [McAPI/McAPI#10]
When testing, I found that supplying bad IPs, rather than resulting in a timely error, would result in a timeout and a CloudFlare error page. The API should set a reasonable seconds timeout limit (or allow one to be supplied) before returning an error.

**Comment by jan-krueger** [comment]
Do you have any example IP that I can use to repoduce the bug because some malformed IPs are producing no error at all?

**Comment by meyerzinn** [comment]
Well, it just started working again for me. I’m trying to integrate this with shields.io so people can have server status shields.

**Comment by meyerzinn** [comment]
I've found that requests that might resolve to A records but don't lead to a server occasionally hang and result in the above. Not sure if it's a client issue.
