### ISSUE TITLE
Useful Status Codes and More

### ISSUE THREAD

**Issue by meyerzinn** [McAPI/McAPI#11]
It'd be awesome if the Server API returned useful status codes depending on the server's status and errors only when errors occurred. Eg., if a server is offline, that's not an error. If the API is broken, that's an error. Also, semantically, single-word messages should typically be lowercase (i.e. "error"), for easier comparison in code. Here is what I propose:
### Use HTTP status codes for server errors.

If the API's cache breaks or something, it should return

``` json
{
    "result": {
        "statusCode": 500,
        "status": "error",
        "message": "An internal error occured."
    }
}
```

Thus, the messages can change to fit the purpose, while the status code remains the identifier (for production). This means more useful error codes can be provided.
### Add an online field.

If a server is online, the API should return

``` json
{
    "result": {
        "statusCode": 200,
        "status": "success"
    },
    "online": true,
    "hostname": "play.hivemc.eu",
    "players": {
        "max": 20000,
        "online": 6126
    },
    "updated": {
        "time": "2016-07-28 23:45:17",
        "expires": "2016-07-28 23:50:17",
        "zone": "Europe\/Berlin"
    }
}
```

Note how `message` is omitted--the beauty of JSON is that it doesn't have to be present to be valid. If the status code is 200 and the status is (note this as well) success, what could the message possibly add?

Here's what I would use for status codes:
- `error` to indicate an error occurred.
- `success` to indicate an operation was successful.

`Ok` isn't as affirmative as `success`.

**Comment by jan-krueger** [comment]
Thank you for all the detailed suggestions. They will be included in the next minor update. This might take a bit of time because I am currently on vaction.

**Comment by meyerzinn** [comment]
If you need any help on this project, I'd be glad to lend a hand 👍 . That, or just open source it and let us all help 😄 .

**Comment by jan-krueger** [comment]
I considered to open-source it, but I am not sure about this yet. :) Thank you for your help offer. :)

**Comment by jan-krueger** [comment]
But instead of including the status code in the JSON response I will use the HTTP status code to indicate errors or success.

**Comment by meyerzinn** [comment]
@sweetcode It's good to include things like internal errors in the head, but for things like server not found keep a 200 OK status because the query did succeed from a request router perspective.

**Comment by jan-krueger** [comment]
Good point.

**Comment by jan-krueger** [comment]
New open-source repo available at https://github.com/McAPI/mcapi-3.0 - Including improvements to a more solid status code system.
