### ISSUE TITLE
Version 3.0 Suggestions

### ISSUE THREAD

**Issue by jan-krueger** [McAPI/McAPI#13]
I decided that Version 2.3.x will be the last iteration of the current minor version cycle. The next huge changes will be in Version 3.0. In the meantime I will keep publishing bug fixes but no new features or anything else. 

The currently used version is written in Slim 3 and it was fine and doing well until the project became one of my side projects to a main project and I think it is time to switch to a framework that fulfills this role perfectly without any flaws: Laravel. - Laravel has a huge community and is perfectly for a project with this scale and future. It receives updates on a frequent basis. It is also open-source. It is lightning fast and it also offers access to so many community packages which can be easily included.

In next few weeks I will start to create a basic concept and really basic code structure to figure out what kind of implementation will be bulletproof and easy expandable in the future.

_This is a discussion thread so feel free to discuss. :)_ 

---
# Contributor Covenant Code of Conduct
## Our Pledge

In the interest of fostering an open and welcoming environment, we as
contributors and maintainers pledge to making participation in our project and
our community a harassment-free experience for everyone, regardless of age, body
size, disability, ethnicity, gender identity and expression, level of experience,
nationality, personal appearance, race, religion, or sexual identity and
orientation.
## Our Standards

Examples of behavior that contributes to creating a positive environment
include:
- Using welcoming and inclusive language
- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community
- Showing empathy towards other community members

Examples of unacceptable behavior by participants include:
- The use of sexualized language or imagery and unwelcome sexual attention or
  advances
- Trolling, insulting/derogatory comments, and personal or political attacks
- Public or private harassment
- Publishing others' private information, such as a physical or electronic
  address, without explicit permission
- Other conduct which could reasonably be considered inappropriate in a
  professional setting
## Our Responsibilities

Project maintainers are responsible for clarifying the standards of acceptable
behavior and are expected to take appropriate and fair corrective action in
response to any instances of unacceptable behavior.

Project maintainers have the right and responsibility to remove, edit, or
reject comments, commits, code, wiki edits, issues, and other contributions
that are not aligned to this Code of Conduct, or to ban temporarily or
permanently any contributor for other behaviors that they deem inappropriate,
threatening, offensive, or harmful.
## Scope

This Code of Conduct applies both within project spaces and in public spaces
when an individual is representing the project or its community. Examples of
representing a project or community include using an official project e-mail
address, posting via an official social media account, or acting as an appointed
representative at an online or offline event. Representation of a project may be
further defined and clarified by project maintainers.
## Enforcement

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the project team at **mcapi _at_ krueger _minus_ jan _dot_ de**. All
complaints will be reviewed and investigated and will result in a response that
is deemed necessary and appropriate to the circumstances. The project team is
obligated to maintain confidentiality with regard to the reporter of an incident.
Further details of specific enforcement policies may be posted separately.

Project maintainers who do not follow or enforce the Code of Conduct in good
faith may face temporary or permanent repercussions as determined by other
members of the project's leadership.
## Attribution

This Code of Conduct is adapted from the [Contributor Covenant](http://contributor-covenant.org), version 1.4,
available at [http://contributor-covenant.org/version/1/4](http://contributor-covenant.org/version/1/4/)

---

**Comment by meyerzinn** [comment]
I like the code of conduct 👍 . Also, would you consider a NodeJS implementation? It's generally the best for this sort of data (cache with Mongo, ezpz).

**Comment by meyerzinn** [comment]
## Move version 3 to a versioned URL.

This would mean using `/api/v3/`.. for URLs. Continue like this for future API versions. Maybe keep a few outdated instances running.

**Comment by meyerzinn** [comment]
I've been working on documenting how I think the API should work.

http://docs.mcapide.apiary.io/#

Take a look and see if it's doable. The `filter` mechanism is easy with NodeJS (NPM has some great packages for it) but I'm not so sure about PhP.

**Comment by jan-krueger** [comment]
@20zinnm Thank you for the whole work you are putting in this project already. I would like to check out your plan but unfortunately the link is set to 'private' (This documentation is private and can be viewed only by owner, editors or allowed viewers. Please log in.  <- Signed in threw GitHub) and currently not accessible for me. :)

The reason for using PHP is that I am using it for 6 - 7 years now and it's beside Java the most comfortable to use (script) language for me, that is why I will stick with it. The latest major update to PHP7 also increased the speed of it by ca. 50%. I hope it's okay. :) 

PS: I will answer your question if it is doable as soon as I could check out your work. :)

**Comment by meyerzinn** [comment]
Sorry, @sweetcode, please try again. Also, http://www.zdnet.com/article/how-replacing-java-with-javascript-is-paying-off-for-paypal/. Node is simply faster than PhP for things like this because PhP is a scripting language. It's a powerful scripting language, but in the end, it's hard and inefficient to have running tasks in PhP. For the API, it'd be so much faster if inbound requests were handled by an already running server instead of a script that has to start up and connect to databases.

**Comment by jan-krueger** [comment]
@20zinnm Yep, totally agree that NodeJS is extremly fast and powerful, the problem is just that I have never used it before and I have no clue how to work with it especially if it comes to stuff like sending packets/sockets and other networking stuff that is required e.g. to get information from Minecraft servers. 

You seem to be interested in developing it in NodeJS due to your open issue :), but I also would have to learn a new language what I don't mind at all escpially because JS seems to be kind of the new industry standard. - If I decide to learn the new language, it would be nice if you would join the team due to the lack of my experience with the language it would be huge plus to have you on board. In this case, we have to consider that that in 4 weeks a new school years starts for me, and because this will be the last year I have to do great, but this kind of details should be discussed in a private chat or something compareable. :)      

Let me know what you think about joining the project. :)

**Comment by meyerzinn** [comment]
@sweetcode I'm all in if you want me to. I have school too, but weekends are still open 😄.  The main thing for NodeJS is to use ExpressJS to make a RESTful API. Past understanding express it's basically JavaScript. Some benefits:
1. There are a ton of cache packages we can use to cache data, as well as a million other packages for everything else. https://www.npmjs.com/package/cacheman
2. Using MongoDB, we can automate data expiration (instead of a traditional cache, just expire data).
3. You can literally export from programs like apiary.io a working NodeJS server based on the API specs.
4. Everything being JavaScript, JSON is the data model of choice. Fits with the API.

**Comment by meyerzinn** [comment]
Speaking of, https://www.npmjs.com/package/minecraft-pinger

**Comment by meyerzinn** [comment]
https://www.npmjs.com/package/minecraft-protocol for the full protocol.

**Comment by meyerzinn** [comment]
@sweetcode I'll keep working on my improved docs.

**Comment by TuxCoding** [comment]
Isn't Lumen way better for a project like this?

**Comment by meyerzinn** [comment]
I happen to know a bit of PhP, and I think @games647 is right--Lumen would be a better option than Laravel. However, I still think NodeJS would be the best candidate if a total rewrite is in order.

**Comment by Blackbird1604** [comment]
So is this still active & alive?

**Comment by jan-krueger** [comment]
@Blackbird1604 Yep, it is. In the meantime I did some small improvements to the still closed-source version 2.0 as you can see in the changelog, however I hope that I can start working on 3.0 sooner than later. The new project will definitely be open-source.

**Comment by jan-krueger** [comment]
New open-source repo available at https://github.com/McAPI/mcapi-3.0
