### ISSUE TITLE
Heads API

### ISSUE THREAD

**Issue by meyerzinn** [McAPI/McAPI#15]
This has been one of my ideas for a while now, but I think you could help me make it a reality.

Basically, mapmakers and creative servers love to offer players custom heads; that is, textured heads that resemble blocks or other objects. However, to display custom heads, one must acquire a Mojang-signed texture via the sessions service in order to have vanilla clients render custom skins. This was to prevent servers from giving players custom skins and such. Currently, the largest database of heads is (to my knowledge) http://heads.freshcoal.com. This API would allow for more heads to be generated than if done manually.

Database:

``` javascript
{
    "_id": "mongo id",
    "source": "https://minotar.net/skin/clone1018",
    "createdAt": "...",
    "base64": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAIAAAAt/+nTAAAEuklEQVR4nMxYa2gcVRS+MzuPbDfbdZe01NLgPxtFSWmKsbU+sLolqRpiqz+sWEUhtESQKCWoUFGKD1D8YVGpluILxIIggSAtoliMjyw+f9g/gSD4o9E17TZud3Z2xjNz2rO3986d3ZDs2sPlcu45595853XnbnSmplwu14wqF1LMOS0lpQOECRlhLhaLvA0uLy8SgsovD963hVfB8nLMgBBUCvmL92+RjZ/c1rPsyJqkuB5AEmrJcb3WIlokNegBuTaMRGOf20mGSgE1Q83KLnoCS9Mwqq4rtEHStlqKMoaaLaFiSCgBH3iD/xF9Y6I7vuFlH6ltw+2ksajrHIvn6cHeTDb78uQvY7f3GLpW87xXvzjF306RG1mbPwuq+/7grs3IvL5n25GRAeRfe/A2FtXfTWapFaTzIPiuTXbYvu/33vD2yg7LTqWAgWVXppNd7G/+FNzF9wlrS/3UHSDo74wMomRNV/b90bv3bz1udaY0ywIGloZpovaFoY28GzLWtqXCoOBdmN1q4Majd56vOE99PEWXKc5H9u4A1WPvHrcti3G13v7AE2nE4dW+Mps9cGyKYH30xPC/p+eAX7F61eh7XwHzynDf/k8Lz+3sL82fgeUzn3xDuOXejRQuswMH7r3RtgzbNG3b1t3qs5/9KNxFPM+/Q5/fcb3ja1ekkrNzxVrNr1SC1F3ZlRn74EvcAh1/en7hpYkfWusAv9jU3RlpNP3HuUg52O8bvHmh4hi67jPm+X6Habw1efJ3vRxpf262FilP50w/HTyxtJJusrTwCIgn5VOiSXI9z615FcdlzNcTCXAA5VYpI1g66TOqQxD9Baa0OADL8DLzah7kUdODo7Qln8ZfG83YLzUDQFYYdad2SXnExFsmqBwqIcaiy0y5F+t+rlxZlbQbWoNZ0atnvMdLwrx3YOvZcgWYFbZ5+PPgUqIeIGRLJ1X/xJXQXAiLp0gn35w8aRoJGIi+b1OW1z5yrdgMKgJvMSJEsAxzEke6DFTGLavwXIg0BvvoiW9hIPrC9D9kQD7QUgUI5OtTtmxDwjgHmCK0kejlkji1UIEB0BE98KQC46nfHGAe7k8DLFVFRaInJj4POo9eiD3ISSKo+DaAv/3ArWuAB/SQEFSRAUjIB6bIAKHnneeXMXlY9L1HHx1yAIse0bNLGxfhwhLMNl8XPJ+OfleSk4Clz3/+8BCcUav6mCbgFnpo39j52Z/WZqwYhsbf1Rqzfdq/vW81jz74245GBgEfzrCrPK91r05sWGf/PFPlTwDq8k1yHlT1WzU86i/NBYM/zzqRDuh37B498eEbqniDCgwEIZXB7o1rRfRchfA8ABJqiac6eonotlAhDGh8fJznhaVgDCUEo/OqBIyR4W5IIPIwUEVaWpIEBtg/PpCDkc/nJyYmmp9V4DWASBmgbPBpEVJEjYXVCbGRI4flKwuRwZqeWaj/oqBf0vJ/XZn0Dx6BElDitJj59fv+e/asW7/h62OHeSG/4ereW4bu2mloHUP5XfOuAXPAo4TmalKUhPaBPNx10/ahQqFQ//maTCIPTLkcVAvMwKMWeZTLZAjdPX3oUKQdUf6aeH2zJERUfrrRey7+VfdfAAAA//9cNJBMy0YAOgAAAABJRU5ErkJggg==",
    "skin": "eyJ0aW1lc3RhbXAiOjE0MjAzMDE3MzYwMjIsInByb2ZpbGVJZCI6ImQ5MTM1ZTA4MmYyMjQ0Yzg5Y2IwYmVlMjM0MTU1MjkyIiwicHJvZmlsZU5hbWUiOiJjbG9uZTEwMTgiLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Q5Y2E1NWU5ODYyZjAwM2ViZmExODcyYTkyNDRhZDVmNzIxZDZiOWU2ODgzZGQxZDQyZjg3ZGFlMTI3NjQ5In19fQ=="
}
```

How the API works:
`GET /heads/:src`:

Fetch the image located at `:src` (given it's a PNG) and make sure it's a proper skin (no point wasting API calls and resources). Base64 encode it. If the database contains a signed skin (texture) with the same base64 input, simply fetch the signed skin (texture) and send it with status code `200`. `200` indicates we have the skin requested and it is included in the body.

If the image is not in the database, here's the fun part: Add it to a queue collection (database table) and send `202 Accepted`, meaning we have queued the skin and you should check back later. A few Minecraft accounts should be processing the queue, setting their skin to the queued skin (via Mojang's API). Once they are done, publish the skin to the actual database. Next time the client requests that image, the signed skin is already in the database!

If the image is not a skin (bad dimensions), of the wrong type, or the src was inaccesible, something happened to make the image unprocessable, return code `400 Bad Request`.

`GET /heads?offset=x&limit=y` will return a paginated list of all the current skins in the database (for a website or plugin).

This would be a very ambitious project, but if it succeeds it would be amazing.

**Comment by meyerzinn** [comment]
For Queueing Skins, I just found Kue (by Automattic). It fulfils the need perfectly. https://github.com/Automattic/kue

**Comment by jan-krueger** [comment]
Closed due to low request rate on image endpoints. I collected metrics data about the usage of endpoints and the image endpoints were only rarely used.
