### ISSUE TITLE
Can't Retrieve UUID

### ISSUE THREAD

**Issue by creatorfromhell** [McAPI/McAPI#16]
When I send a GET request to gather a player's uuid from a username as stated in the [documentation](https://mcapi.de/user), I just get a Moved Permanently status code.

**Comment by jan-krueger** [comment]
Thank you for your feedback, would you mind providing more details about your request causing this issue. - I tested it with the username 'Notch' and it worked perfectly. I will add in the next few days the option to see what node was used to answer the request, it might be related to a misconfiguration of the node system.

 edit: 
Okay, another point came to my mind while thinking about this. I am re-routing all traffic from port 80 to port 443 (HTTPS connection) and to make this clear I return a 301 HTTP status code which is the HTTP code for _Moved Permanently_. Maybe your browser/software doesn't allow redirections. @creatorfromhell

**Comment by jan-krueger** [comment]
Could you resolve the problem or does it still exist? @creatorfromhell
