### ISSUE TITLE
Ability to bulk player name -> UUID

### ISSUE THREAD

**Issue by creatorfromhell** [McAPI/McAPI#17]
As a plugin developer I find that this feature would be very useful. It would add the ability to bulk convert player names to UUID. The format could be something such as:
`GET https://mcapi.de/api/user/["name", "name1", "name2"]`
Then on the API end you could check to see if it's a username or JSON Array, or alternatively you could have it be a separate URL such as:
`GET https://mcapi.de/api/users/["name", "name1", "name2"]`

On your side of things it'd be beneficial to add a limit to how many usernames you're able to convert per call.

**Comment by jan-krueger** [comment]
Thank you for the suggestion. It will be part of 3.0. No release date yet due to final exams and I have to focus on school for this. :)
