### ISSUE TITLE
The Service is cooling down..

### ISSUE THREAD

**Issue by Blackbird1604** [McAPI/McAPI#18]
Hi,

ich krieg die seit mehreren Tagen nurnoch folgende Fehlermeldung bei Userabfragen, die (anscheinend) nicht im Cache sind:
Beispiel: https://mcapi.de/api/user/1a8f06f7a4e741fd8515e434f8630b3e
Result :{"result":{"status":"The service is currently cooling down and cannot perform any requests. Please try it later again.","message":"No errors."},"username":null,"uuid":"1a8f06f7a4e741fd8515e434f8630b3e","premium":false,"history":null,"properties":{"raw":[],"decoded":[]},"updated":{"time":null,"expires":null,"zone":"Europe\/Berlin"}}

Jetzt meine Frage woran liegt das? Mache ich etwas falsch?

**Comment by jan-krueger** [comment]
Nein, du machst alles richtig. Ich habe leider immer noch Problem mit dem Mojang Request Limit, was sich wohl auch nie vollständig lösen lassen wird. Ich hoffe das Digital Ocean zeitnah mir erlaubt mehrere IPv4 Adressen an meinen Server zu binden und/oder die Mojang API endlich IPv6 Adressen unterstützt. 

Das aktuelle System ist fertig und auch schon im Einsatz und ich müsste nur weitere IP Adressen in meine Datenbank eintragen, aber dies geht aktuell leider, aus den oben genannten Gründen, noch nicht. 

Die Cache Tabelle enthält aktuell um die 280.000 Einträge und ist bei dieser Anzahl mehr oder weniger stabil. - Ich hoffe, die meisten Anfragen an den Cache auslagern zu können, allerdings muss ich auch eine gewisse Aktualität gewährleisten weshalb ich Cache-Einträge die 24 Stunden alt sind update mit neuen Informationen, wenn sie abgerufen werden. 
Ich habe im Durchschnitt 8k/10 Minuten Zugriffe auf den User Endpoint und die alle auch immer ggf. aktuell zu halten ist leider nicht möglich. Was du also siehst ist der Zeitpunkt, wenn du eine Anfrage stellst, die es noch nicht in der Datenpank gibt und eine Abfrage benötigt, allerdings der Server aktuelle keine Anfragen an die Mojang API mehr "frei" hat.

Mögliche Lösungen:

- Server Anbietern wechseln (sehr ungerne, da bereits Guthaben aufgeladen und vertraut mit der Infrastruktur so wie Zuverlässigkeit)
- Cache Time auf mehrere Tagen erhöhen (möglich, allerdings mit dem Nachteil noch ältere Informationen verteilen zu müssen)
- und die bereits oben gennanten, allerdings bin ich dabei von den Entscheidungen Dritter abhängig.

Ich muss mir noch überlegen was ich machen werden, aber du bist natürlich auch zu einer Diskussion eingeladen.
