### ISSUE TITLE
API request returns an error

### ISSUE THREAD

**Issue by xwolfyxNL** [McAPI/McAPI#21]
Hello when I for example enter this URL: https://mcapi.de/api/user/xwolfyxNL

I am getting this error:
{"result":{"status":"The service is currently cooling down and cannot perform any requests. Please try it later again.","message":"No errors."},"username":"xwolfyxNL","uuid":null,"premium":false,"history":null,"properties":{"raw":[],"decoded":[]},"updated":{"time":null,"expires":null,"zone":"Europe\/Berlin"}}

Could you maybe look in to this issue?

**Comment by jan-krueger** [comment]
Hi, I have explained this behaviour in #19 & #20 . If you have any more questions about the topic feel free to ask.

~ Jan

**Comment by xwolfyxNL** [comment]
Alright thank you. Keep up the good work!
