### ISSUE TITLE
validating mcapi.de/AAAA: no valid signature found

### ISSUE THREAD

**Issue by Nedjii** [McAPI/McAPI#22]
I got this in my debian syslog "validating mcapi.de/AAAA: no valid signature found" That's spaming my logs, i don't even know what mcapi is, do you know what this error is and what it could cause to my server ?

**Comment by jan-krueger** [comment]
Hi,

McAPI is a web API for the game Minecraft. Developers can send a request to my server and my server will answer it with certain pieces of information.

Based on the error message and just googling it I couldn't find a satisfying answer. However, do you run a Minecraft server on your server? Do you run any third-party web applications for other people on your server? 

Can you send the log containing these errors projects [at] krueger-jan.de?

**Comment by Nedjii** [comment]
Yes i'm running a minecraft server but i do not know any plugin using your api, it seems that a plugin is failing sending a request to your server, do you know what i could cause to my minecraft server ?

**Comment by jan-krueger** [comment]
Can you give me the list of plugins you are using on your server? I might be able to identify the plugin.

**Comment by Nedjii** [comment]
ColoredSigns, CustomOreGen, PlaceholderAPI, TuxTwoLib, PlugMan, ConsoleScheduler, WorldEditFix, SuperTrails, ViaVersion, WorldEdit, Skript, MineJoinMessage, ClearLag, ChatControl, SkQuery, WorldBorder, MessageAnnouncer, BannerBoard, EasyBackup, ProtocolLib, AntiWDL, Skellett, MVdWPlaceholderAPI, IPWhitelist, WildSkript, DeluxeMenus, MysteryBoxes, PermissionsEx, FeatherBoard, EffectLib, StaffChat, Vault, MineWeb_BukkitBridge, WorldGuard, Spartan, AuctionHouse, ASkyBlock, Umbaska, SkExtras, boosCooldowns, CustomPayloadFixer, Essentials, LiteBans, SilkSpawners, Multiverse-Core, TradeMe, SimplePrefix, MineResetLite, ChestShop, NoFlyZone, HolographicDisplays, TuSKe, MakeYourOwnCommands, SkinsRestorer, skRayFall, LeaderHeads, EssentialsSpawn, WorldGuardExtraFlags, CommandSigns, CS-CoreLib, TAB

**Comment by jan-krueger** [comment]
It might be SkinsRestorer. Do you have a link to the plugin because there seem to be several plugins and what version of it are you using?

**Comment by Nedjii** [comment]
I just want to know if that can cause lag, don't lose your time if it doesn't ^^

**Comment by jan-krueger** [comment]
Yes, it can cause lag if it is sending a synchronous request because this blocks the main thread of the server for a couple of ms. You should contact the developer of the plugin. 

It's fine I currently have some free time. Cheers. :)

**Comment by Nedjii** [comment]
Are you sure it is skinsrestorer ?

**Comment by jan-krueger** [comment]
No, not 100% but I know that SkinRestorer at some point used my API. I googled for the plugin and found several plugins named SkinRestorer, so can you give me the exact link to the project page of the plugin and which version are you using, so I can check whether or not it is this plugin?

**Comment by Nedjii** [comment]
Sure, https://www.spigotmc.org/resources/skinsrestorer.2124/ I'm using last version (13.1.3)

**Comment by jan-krueger** [comment]
According to this change-log, they are using McAPI - https://www.spigotmc.org/resources/skinsrestorer.2124/update?update=141876

**Comment by Nedjii** [comment]
Thanks, i'm gonna ask the dev

**Comment by Nedjii** [comment]
I asked, they are not using mcapi anymore xd

**Comment by Nedjii** [comment]
Maybe it is placeholderapi ?

**Comment by jan-krueger** [comment]
I don't think so... it is really hard to tell which plugin is causing it. I think you probably have to go to each of their sites and check if they are using it.

**Comment by Nedjii** [comment]
I think that's freezing my server...

**Comment by Nedjii** [comment]
Couldn't you find where is my problem looking at my server's resquests ?

**Comment by jan-krueger** [comment]
I didn't receive any email yet. 

Edit: I just got the email a couple of minutes ago. It seems as if I have to setup DNSSEC to resolve the error. I will do that in the next couple of days not 100% sure if this will fix the error.

**Comment by Nedjii** [comment]
Your email  project@krueger-jan.de doesn't seem to work

**Comment by Nedjii** [comment]
I've sent you the email
