### ISSUE TITLE
User Reputation: Bans not working

### ISSUE THREAD

**Issue by austinhuang0131** [McAPI/McAPI#23]
The `services` object is `[]` instead of showing how many bans the user has on each services.

**Comment by jan-krueger** [comment]
The array contains all bans and their reasons if the user was ever banned. I just tested it with Notch and it seems to be working just fine. What exact behavior did you expect and what username/uuid did you use?

https://screenshots.firefoxusercontent.com/images/1581cc4a-7944-492c-a907-026829a33436.png

**Comment by austinhuang0131** [comment]
Let me correct:

IT *sometimes* shows a user's reputation like this: (Notice that the `"time"` is `null`)
```json
{"result":{"status":"success","message":"No errors."},"reputation":10,"services":[],"updated":{"time":null,"zone":"Europe\/Berlin"}}
```

and *sometimes* shows like:
```json
{"result":{"status":"success","message":"No errors."},"reputation":10,"services":{"mcbans":[{"amount":0,"server":[]}],"glizer":[{"amount":0,"server":[]}],"mcbouncer":[{"amount":0,"server":[]}]},"updated":{"time":"2017-10-27 18:31:14","zone":"Europe\/Berlin","expires":"2017-10-27 18:36:14"}}
```

**Comment by jan-krueger** [comment]
Oh okay, thank you. I will look at this. This seems to be an issue with the cache. Is this a random event or could you identify some way to reproduce it?

**Comment by austinhuang0131** [comment]
The first version (Error) seems to be frequent to me. I'm having a hard time reproducing the correct version.

**Comment by jan-krueger** [comment]
I hope that I found a workaround. It seems as if there is some way that the API is requesting data even though it didn't try to fetch them at all. I hope that is the problem, feel free to test and notify if it works or if it is still broken.

**Comment by austinhuang0131** [comment]
Seems to be fixed. Thanks!
