### ISSUE TITLE
Query is enabled but the API doesn't work

### ISSUE THREAD

**Issue by BitSec01** [McAPI/McAPI#24]
I am trying to get the API to work but for some reason it keeps saying.
The server didn't accept the handshake package. (enable-query: false)
I do have the query enabled. and I am using this link: https://mcapi.de/api/server-query/188.165.56.183/31668

**Comment by jan-krueger** [comment]
Hi, what version of Minecraft is the server using?

**Comment by BitSec01** [comment]
@sweetcode I am using spigot 1.12.2. This is my server: 188.165.56.183 port 31668

**Comment by jan-krueger** [comment]
Thank you for reporting this bug. I just tested it with a test server and I can reproduce it, I will look into it and update this issue thread as soon as there is news.

**Comment by jan-krueger** [comment]
@RamonRobben It is working now. I did a mistake in the firewall settings and didn't allow any UDP-in traffic. It also uncovered another bug, your motd does contain some chars that aren't UTF-8 that's why it returns as value "false" currently.
