### ISSUE TITLE
Issue visiting HTTP site. 

### ISSUE THREAD

**Issue by james090500** [McAPI/McAPI#25]
Visiting http://mcapi.de/ in a new browser so it hasn't cache auto redirect. Will result in a cloudflare 502 error. 

![image](https://user-images.githubusercontent.com/20372645/34522560-13467044-f08b-11e7-8619-b7248eeaddbb.png)

**Comment by jan-krueger** [comment]
Thank you for reporting this issue, unfortunately, I am not able to reproduce this error, however, I am now enforcing "HTTPS everywhere", so you should get a 301 HTTP code when you visit it without SSL now.

**Comment by jan-krueger** [comment]
This issue seems to be solved.
