### ISSUE TITLE
CSF and MCAPI

### ISSUE THREAD

**Issue by shukamu95** [McAPI/McAPI#26]
Every time i active CSF FIREWALL my servers get "{"result":{"status":"error","message":"The server didn't accept the handshake package. (enable-query: false)"},"hostname":null,"software":{"name":null,"version":0,"plugins":[]},"players":{"max":0,"online":0,"list":[]},"list":{"motd":null},"map":null}" 

How to solve? I already put all cloudflare IP in allow list.

**Comment by james090500** [comment]
I'm guessing Linux? Check your linux server logs for incoming connections on your query port. 

See where they're getting blocked from there.

**Comment by shukamu95** [comment]
What type of connections MCAPI make when try to get infos about server?

I think is UDP, right? You know how many packets my server send to MCAPI when you handshake us?

**Comment by james090500** [comment]
Opens a UDP socket on your query port. Check your firewall logs for any blocked connections on the port you've set your query.

**Comment by shukamu95** [comment]
Yeah i just find the problem, is about UDP Packets per second i limit on my server.

You know some infos about how many packets MCAPI receive when server reply?

**Comment by james090500** [comment]
MCAPI will send around the same as a normal query request.

**Comment by jan-krueger** [comment]
Good morning, evening and night everyone,

McAPI is strictly following the Minecraft Query protocol which is documented [here](http://wiki.vg/Query). I basically open a UDP connection, (1) send the Handshake packet and when that was successful (2) I send the packet to request the data. - I hope that helps you to resolve the issue.

**Comment by jan-krueger** [comment]
I assume this is resolved if not just re-open this issue, please.
