### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by crysis992** [McAPI/McAPI#29]
When trying to access the beta.mcapi.de I'm getting a 526 error Page from Cloudflare.

`The SSL certificate presented by the server did not pass validation. This could indicate an expired SSL certificate or a certificate that does not include the requested domain name. `

Hope this gets resolved as soon as possible.

**Comment by jan-krueger** [comment]
Thank you for notifying me. The issue has now been resolved.
