### ISSUE TITLE
Player-Command returns wrong information sometimes

### ISSUE THREAD

**Issue by jboeschemeier** [McAPI/McAPI#4]
Hey first of all nice API. So, I tried the player <name> command several times with different names and sometimes it returns a wrong UUID.

Maybe you can take a second lock on this. ^^ Thank you.

**Comment by jan-krueger** [comment]
Sorry to hear you're experiencing problems with the API. If you have not already, please try following the below steps to troubleshoot.
- check the spelling of all words
- type "help" into the console
- make sure that your command doesn't start with a space in front of the command

Kind Regards,
Yonas
