### ISSUE TITLE
Menüoption unerreichbar bei 1280x1024 Auflösung

### ISSUE THREAD

**Issue by ghost** [McAPI/McAPI#5]
Hey,
wenn ich die McAPI Website mit einem alten Bildschirm anschaue sind die Unterpunkte von "Tutorials" außerhalb meines Bildschirms. Ich kann auch nicht nach rechts scrollen da die Leiste wieder verschwindet wenn das Menü zuklappt.

![menü offen](http://i.imgur.com/FFkel7a.jpg)
![menü offen](http://i.imgur.com/swqyygs.jpg)

Systemdaten:
Windows 7
Chrome 49.0
Auflösung 1280x1024

**Comment by jan-krueger** [comment]
Guten Abend,
vielen Dank für deine Rückmeldung. Es tut mir leid das ich mich jetzt erst melde, habe allerdings auch noch viel mit einem anderen Projekt zu tun. - Ich werde mir das die Tage mal anschauen, vielen Dank für deine Rückmeldung.

Mit freundlichen Grüßen,
Jan Krüger

**Comment by jan-krueger** [comment]
Bis der Bug gefixed ist sind hier erstmal die Links für dich, falls du diese benötigst. :)
- http://mcapi.de/tutorials/php (since 2.0 unavailable)
- http://mcapi.de/tutorials/curl (since 2.0 unavailable)

Mit freundlichen Grüßen,
Jan Krüger

**Comment by jan-krueger** [comment]
Vielen Dank,
das Problem sollte jetzt behoben sein. :)
- https://mcapi.de/changelog#v131

Mit freundlichen Grüßen,
Jan Krüger
