### ISSUE TITLE
Add profile properties api

### ISSUE THREAD

**Issue by TuxCoding** [McAPI/McAPI#6]
Based on this

http://wiki.vg/Mojang_API#UUID_-.3E_Profile_.2B_Skin.2FCape

It should be possible to query the encoded and signed properties in order to download skins for ingame usage.

**Comment by jan-krueger** [comment]
Are you looking for an image like this - http://textures.minecraft.net/texture/f1b58d6787ede3dadabbd7abeebf59ae917a8179c95e5b84be9ff96ebc1dcf56 - or do you actually need these values itself as strings?

**Comment by TuxCoding** [comment]
No I actually need the data in order to set it ingame.

The important ones are the encoded data and the signature. Optional it would be neat if the encoded data can be seen decoded too. Might be good for debugging.

**Comment by jan-krueger** [comment]
Okay, the next version will contain this feature but I am not sure about the release date yet.

**Comment by jan-krueger** [comment]
@games647 So this is the result you are looking for - http://puu.sh/pOXS3/017bd73214.png, or?

**Comment by TuxCoding** [comment]
I need to the signature too otherwise the client will refuse it.

**Comment by jan-krueger** [comment]
Ok, got that also now.

**Comment by jan-krueger** [comment]
The feature is now available.

**Comment by jan-krueger** [comment]
@games647 Would like to hear some feedback if it is the thing you were looking for and if you're satisfied with it.

**Comment by TuxCoding** [comment]
Definitely what I'm looking for, but should point out that it's only included if use the uuid as a parameter.

**Comment by jan-krueger** [comment]
I am a bit confused: _should_ it only be included if the requests provides an UUID _or_ do you only get it if you provide an UUID, because I get it with the UUID as well as with the username.

If you mean the first case, I can consider to add a boolean value to enable properties or not.

**Comment by TuxCoding** [comment]
It's okay as it is. 

I meant that you just mentions this in the example on the website. It might be confusing for some people.

**Comment by jan-krueger** [comment]
Okay, thank you for the feedback. I will try to make the documentation more clear.

**Comment by TuxCoding** [comment]
Or you return the properties on a name request too. Thanks :D
